R-randtoolbox: Autospec creation for update from version 1.31.0 to version 1.31.1
Version 1.31.1
=============
- clean up test files because tests/test-sobol-scram.R failed
on i386-pc-solaris2.10 (32-bit). Output was
 > umat <- sobol(n=1e5, dim=1111)
  Error: cannot allocate vector of size 423.8 Mb